In [1]:
import torch

In [11]:
t1 = torch.tensor([1, 12, 234], dtype=torch.int8)

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [14]:
torch.ones(3, 4).dtype

torch.float32

In [21]:
torch.ones(3, 4).size(1)

4

In [22]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
t2 = torch.randn(3, 3)
t2

tensor([[-0.7118,  1.9066,  1.1395],
        [-0.9773, -0.2148, -1.2086],
        [ 0.4055, -0.5235,  0.1542]])

In [35]:
torch.randn_like(t2)

tensor([[-0.9793, -0.2875,  0.2434],
        [-0.5800, -1.0474, -0.2047],
        [ 0.6882, -0.7701,  0.4629]])

In [36]:
import numpy as np

In [41]:
arr1 = np.array([[1, 3, 34], [11,23,1234]])
arr1

array([[   1,    3,   34],
       [  11,   23, 1234]])

In [40]:
torch.from_numpy(arr1)

tensor([ 1,  3, 34])

In [45]:
arr1[0, :2]

array([1, 3])

In [47]:
t2

tensor([[-0.7118,  1.9066,  1.1395],
        [-0.9773, -0.2148, -1.2086],
        [ 0.4055, -0.5235,  0.1542]])

In [51]:
t2[0:3, :2]

tensor([[-0.7118,  1.9066],
        [-0.9773, -0.2148],
        [ 0.4055, -0.5235]])

In [53]:
torch.tensor([[1, 2, 3], [2, 2, 1]])

tensor([[1, 2, 3],
        [2, 2, 1]])

In [64]:
t3 = torch.rand(3, 2, 3, 4)
t3

tensor([[[[0.7590, 0.6226, 0.5232, 0.5378],
          [0.6528, 0.7771, 0.7764, 0.8093],
          [0.5663, 0.4102, 0.7466, 0.0423]],

         [[0.2373, 0.5716, 0.5705, 0.9075],
          [0.6492, 0.2842, 0.1972, 0.4192],
          [0.9028, 0.4138, 0.0820, 0.5876]]],


        [[[0.8280, 0.0570, 0.3047, 0.3500],
          [0.0013, 0.8183, 0.3853, 0.9168],
          [0.0541, 0.1820, 0.3226, 0.0242]],

         [[0.1896, 0.9456, 0.7938, 0.8068],
          [0.3081, 0.2128, 0.5726, 0.9211],
          [0.6532, 0.6860, 0.8176, 0.6388]]],


        [[[0.9066, 0.5834, 0.5327, 0.4638],
          [0.4910, 0.1660, 0.1562, 0.7241],
          [0.5788, 0.0363, 0.3767, 0.6039]],

         [[0.0233, 0.1773, 0.5000, 0.5396],
          [0.9966, 0.0386, 0.4048, 0.5062],
          [0.1411, 0.6393, 0.2990, 0.6919]]]])

In [62]:
id(t3.t()) == id(t3)

False

In [63]:
id(t3.transpose(1, 0)) == id(t3)

False

In [66]:
t3.permute(3, 2, 0, 1).shape

torch.Size([4, 3, 3, 2])

In [67]:
t3.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [68]:
torch.save(t3, "test.pt")

In [69]:
t4 = torch.load("test.pt")

In [71]:
torch.all(t4 == t3)

tensor(True)

In [73]:
x = torch.tensor(2.)
w = torch.tensor(3., requires_grad=True)
b = torch.tensor(4., requires_grad=True)

In [75]:
x

tensor(2.)

In [76]:
b

tensor(4., requires_grad=True)

In [77]:
y = w*x + b

In [78]:
y

tensor(10., grad_fn=<AddBackward0>)

In [79]:
y.backward()

In [81]:
b.grad

tensor(1.)